//
//  Image+Extensions.swift
//  FemoCare
//
//  Created by MacMini on 06/01/2025.
//



import Foundation
import SwiftUI

extension Image {
    static var appImage = AppImage()
}

struct AppImage {
    let invoice = Image("Invoice")
    let recept = Image("Recept")
    let receipt = Image("Receipt")
    let frame = Image("Frame")
    let rentalimage = Image("RentalImage")
    let tickk = Image("Tick")
    let reload = Image("Reload")
    let profile = Image("Profile")
    let messages = Image("Messages")
    let properties = Image("Properties")
    let dashboard = Image("Dashboard")
    let apartment = Image("Appartment")
    let allen = Image("Allen")
    let bell = Image("NotificationBell")
    let camera = Image("Camera")
    let logout = Image("LogOut")
    let blockeduser = Image("BlockedUser")
    let settings = Image("Settings")
    let favorite = Image("favoriteproperties")
    let editaccount = Image("EditAccount")
    let sidemenu = Image("SideMenu")
    let jennifer = Image("Jennifer")
    let myprofile = Image("MyProfile")
    let map = Image("Map")
    let locationn = Image("Locationimage")
    let location = Image("Location")
    let google = Image("Google")
    let apple = Image("Apple")
    let eye = Image("Eye")
    let tenantlogo = Image("TenantLogo")
    let shedule = Image("Schedule")
    let greenrectangle = Image("GreenRectangle")
    let elipse1 = Image("Ellipse1")
    let elipse2 = Image("Ellipse2")
    let filterr = Image("Filter")
    let calendarsidemenu = Image("CalendarSideMenu")
    let food = Image("Food")
    let linkcare = Image("LinkCare")
    let links = Image("Links")
    let career = Image("Career")
    let educare = Image("Educare")
    let personality = Image("Personality")
    let beauty = Image("Beauty")
    let heart = Image("Heart")
    let shopping = Image("Shopping")
    let clockicon = Image("clockIcon")
    let orderIcon = Image("Ordericon")
    let QuestionCamera = Image("questioncamera")
    let eyes = Image("Eye")
    let daughter = Image("Daughter")
    let mother = Image("mother")
    let homelogo = Image("homelogo")
    let dailytask = Image("dailytask")
    let edwardpicture = Image("edwardpicture")
    let homefilter = Image("Filter")
    let homecamera = Image("camera?")
    let HomescreenImage = Image("HomeScreenImage")
   // let sidemenu = Image("SideMenuBar")
    let AvatarImage1 = Image("Avatar1")
    let AvatarImage2 = Image("Avatar2")
    let AvatarImage3 = Image("Avatar3")
    let AvatarImage4 = Image("Avatar4")
    let AvatarImage5 = Image("Avatar5")
    let SplashImage = Image("SplashImage")
    let flag  = Image("Flag")
    let ProfileCricle =  Image("ProfileCricle")
  //  let profile =  Image("Profile")
    let AddCircle =  Image("addcircle")
    let ModeData =  Image("More")
    let CropImage =  Image("Crop")
    let CircleImage =  Image("CircleImage")
    let Editprofile =  Image("Editprofile")
    let Camrabackground =  Image("Camrabackground")
   // let Camra =  Image("Camra")
    let menu =  Image("menu")
    let Background =  Image("Background")
   // let map =  Image("map")
    let Favorite =  Image("Favorite")
    let Logout =  Image("Logout")
    let Filter = Image("Filter")
    let BlackMenu = Image("BlackMenu")
    let homeTiktok = Image("homeTiktok")
    let Will = Image("Will")
    let spencer = Image("spencer")
    let Starmap = Image("Starmap")
    let favouriteicon = Image("favouriteicon")
    let starYoutube = Image("StarYoutube")
    let starTiktok = Image("StarTiktok")
    let starinstagram = Image("Starinstagram")
    let starSnack = Image("StarSnack")
    let ALEX = Image("ALEX")
    let deliveryTime = Image("deliveryTime")
    let Subtract = Image("Subtract")
    let Cliks = Image("Cliks")
    let userImage = Image("userImage")
    let Seen = Image("Seen")
    let filter = Image("filter")
    let CategoriesImage = Image("CategoriesImage")
    let FollowersImage = Image("FollowersImage")
    let pricerange = Image("pricerange")
    let plateforms = Image("plateforms")
    let ConnectSport = Image("ConnectSport")
    let Menu = Image("Menu")
    let dost = Image("3 dost")
    let Avatar = Image("Avatar")
    let Mail = Image("Mail")
    
}
